### ISSUE TITLE
Errors when start

### ISSUE THREAD

**Issue by ynvkf** [d-Rickyy-b/Python-BlackJackBot#102]
![Screenshot_1](https://user-images.githubusercontent.com/81996771/113668705-4ecc6180-96bb-11eb-8e61-1726d40ec6ab.png)

help

**Comment by d-Rickyy-b** [comment]
Hi, which version of python-telegram-bot are you using?

**Comment by morefuck** [comment]
Hello, I newbie in python. I'm not sure, but maybe latest. I download from this https://github.com/python-telegram-bot/python-telegram-bot folder telegram and moved it to scripts folder.
