### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DO97** [d-Rickyy-b/Python-BlackJackBot#36]
1. "Stop" button is a bit confusing. Sometimes people exchange it as the "No more card" button.

2. Instead of a double /start command to play, maybe there should be a /new command for a new game and /start command to start the game.

3. Replace the X in: "✖️Players who busted" with ❌.

**Comment by d-Rickyy-b** [comment]
For the rework I have done the following:

1. There no longer is a stop button. You need to use the /stop command now
2. Haven't done such a thing yet
3. I replaced the X emoji as you suggested.
