### ISSUE TITLE
Can't start new game

### ISSUE THREAD

**Issue by kipariz** [d-Rickyy-b/Python-BlackJackBot#78]
I started a new game, after few previous.In this new game i had 21 and Dealer had 25 from the start.
I can't stop the game I also can't start new game.
Look like a bug.

![image](https://user-images.githubusercontent.com/47273592/70207661-25e93480-1734-11ea-895d-3940b0be0fc2.png)

**Comment by d-Rickyy-b** [comment]
Hi, I restarted the bot. Can you check if you can still reproduce the issue?

**Comment by kipariz** [comment]
![S91208-11210692](https://user-images.githubusercontent.com/47273592/70429097-95d32400-1a80-11ea-941b-0710f00a159b.jpg)
![S91208-11243020](https://user-images.githubusercontent.com/47273592/70429108-9cfa3200-1a80-11ea-8112-75f1fcc22dc9.jpg)
Have something like this, seems that is ok now.
